server:
  port: 8762
spring:
  application:
    name: config-server
  cloud:
     config:
      server:
        git:
         uri: https://github.com/qwe2673356/spring-cloud-config.git
         searchPaths: config
         username: 834165741@qq.com
         password: qwe2672112
         default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true